// using System.Collections.Generic;
// using System.Linq;
// using System.Text;
// using Microsoft.CodeAnalysis;
// using Microsoft.CodeAnalysis.CSharp.Syntax;
// using Microsoft.CodeAnalysis.Text;
//
// namespace Assembler.Generators;
//
// [Generator]
// public class EnumFromTypeHierarchyGenerator : ISourceGenerator
// {
// 	private const string DisplayString = "Assembler.Generators.Attributes.GenerateEnumFromTypeHierarchyAttribute";
//
// 	public void Initialize(GeneratorInitializationContext context)
// 	{
// 		context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
// 	}
//
// 	public void Execute(GeneratorExecutionContext context)
// 	{
// 		if (context.SyntaxReceiver is not SyntaxReceiver receiver)
// 		{
// 			return;
// 		}
//
// 		foreach (var classDeclaration in receiver.CandidateClasses)
// 		{
// 			var model = context.Compilation.GetSemanticModel(classDeclaration.SyntaxTree);
//
// 			if (model.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
// 			{
// 				continue;
// 			}
//
// 			var attribute = classSymbol.GetAttributes()
// 				.FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == DisplayString);
//
// 			if (attribute == null)
// 			{
// 				continue;
// 			}
//
// 			var includeAbstractClasses = GetIncludeAbstractClasses(attribute);
// 			var enumSource = GenerateEnum(classSymbol, includeAbstractClasses, context.Compilation);
// 			context.AddSource($"{classSymbol.Name}Types.g.cs", SourceText.From(enumSource, Encoding.UTF8));
// 		}
// 	}
//
// 	private static bool GetIncludeAbstractClasses(AttributeData attribute)
// 	{
// 		return attribute.ConstructorArguments.Length > 0 && (bool)attribute.ConstructorArguments[0].Value!;
// 	}
//
// 	private static string GenerateEnum(INamedTypeSymbol classSymbol,
// 		bool includeAbstractClasses,
// 		Compilation compilation)
// 	{
// 		var sb = new StringBuilder();
// 		sb.AppendLine("// <auto-generated/>");
// 		sb.AppendLine();
//
// 		var namespaceName = classSymbol.ContainingNamespace?.ToDisplayString();
//
// 		if (!string.IsNullOrEmpty(namespaceName) && namespaceName != "<global namespace>")
// 		{
// 			sb.AppendLine($"namespace {namespaceName}");
// 			sb.AppendLine("{");
// 		}
//
// 		sb.AppendLine($"    public static class {classSymbol.Name}Types");
// 		sb.AppendLine("    {");
//
// 		var derivedTypes = TypeHierarchyHelper.GetDerivedTypes(classSymbol, includeAbstractClasses, compilation);
//
// 		foreach (var (trimmedName, fullName, _) in derivedTypes)
// 		{
// 			sb.AppendLine($"        public const string {trimmedName} = \"{fullName}\";");
// 		}
//
// 		sb.AppendLine("    }");
//
// 		if (!string.IsNullOrEmpty(namespaceName) && namespaceName != "<global namespace>")
// 		{
// 			sb.AppendLine("}");
// 		}
//
// 		return sb.ToString();
// 	}
//
// 	private class SyntaxReceiver : ISyntaxReceiver
// 	{
// 		public List<ClassDeclarationSyntax> CandidateClasses { get; } = [];
//
// 		public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
// 		{
// 			if (syntaxNode is ClassDeclarationSyntax { AttributeLists.Count: > 0 } classDeclaration)
// 			{
// 				CandidateClasses.Add(classDeclaration);
// 			}
// 		}
// 	}
// }