// using System.Collections.Generic;
// using System.Linq;
// using System.Text;
// using Microsoft.CodeAnalysis;
// using Microsoft.CodeAnalysis.CSharp.Syntax;
// using Microsoft.CodeAnalysis.Text;
//
// namespace Assembler.Generators;
//
// [Generator]
// public sealed class EnumFromMembersGenerator : ISourceGenerator
// {
// 	private const string DisplayString = "Assembler.Generators.Attributes.GenerateEnumFromMembersAttribute";
//
// 	public void Initialize(GeneratorInitializationContext context) =>
// 		context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
//
// 	public void Execute(GeneratorExecutionContext context)
// 	{
// 		if (context.SyntaxReceiver is not SyntaxReceiver receiver)
// 		{
// 			return;
// 		}
//
// 		foreach (var classDecl in receiver.CandidateClasses)
// 		{
// 			var model = context.Compilation.GetSemanticModel(classDecl.SyntaxTree);
// 			if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol classSymbol)
// 			{
// 				continue;
// 			}
//
// 			var attr = classSymbol.GetAttributes()
// 				.FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == DisplayString);
//
// 			if (attr is null || attr.ConstructorArguments.Length == 0)
// 			{
// 				continue;
// 			}
//
// 			if (attr.ConstructorArguments[0].Value is not ITypeSymbol filterType)
// 			{
// 				continue;
// 			}
//
// 			var source = GenerateEnum(classSymbol, filterType);
// 			context.AddSource($"{classSymbol.Name}Members.g.cs", SourceText.From(source, Encoding.UTF8));
// 		}
// 	}
//
// 	private static string GenerateEnum(INamedTypeSymbol classSymbol, ITypeSymbol filterType)
// 	{
// 		var sb = new StringBuilder();
// 		sb.AppendLine("// <auto-generated/>");
// 		sb.AppendLine();
//
// 		var ns = classSymbol.ContainingNamespace;
// 		var hasNs = ns is not null && !ns.IsGlobalNamespace;
//
// 		if (hasNs)
// 		{
// 			sb.Append("namespace ").AppendLine(ns.ToDisplayString());
// 			sb.AppendLine("{");
// 		}
//
// 		sb.Append("    public enum ").Append(classSymbol.Name).AppendLine("Members");
// 		sb.AppendLine("    {");
//
// 		var members = MemberHelper.GetMembers(classSymbol, filterType);
//
// 		for (int i = 0; i < members.Count; i++)
// 		{
// 			sb.Append("        ").Append(members[i]);
// 			sb.AppendLine(i < members.Count - 1 ? "," : "");
// 		}
//
// 		sb.AppendLine("    }");
// 		if (hasNs)
// 		{
// 			sb.AppendLine("}");
// 		}
//
// 		return sb.ToString();
// 	}
//
// 	private sealed class SyntaxReceiver : ISyntaxReceiver
// 	{
// 		public List<ClassDeclarationSyntax> CandidateClasses { get; } = [];
//
// 		public void OnVisitSyntaxNode(SyntaxNode node)
// 		{
// 			if (node is ClassDeclarationSyntax c && c.AttributeLists.Count > 0)
// 			{
// 				CandidateClasses.Add(c);
// 			}
// 		}
// 	}
// }