using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;

namespace Assembler.Generators;

[Generator]
public class InjectMethodGenerator : ISourceGenerator
{
	private const string InjectAttributeType = "Assembler.Generators.Attributes.InjectAttribute";

	public void Initialize(GeneratorInitializationContext context)
	{
		context.RegisterForSyntaxNotifications(() => new InjectSyntaxReceiver());
	}

	public void Execute(GeneratorExecutionContext context)
	{
		if (context.SyntaxReceiver is not InjectSyntaxReceiver receiver)
		{
			return;
		}

		foreach (var typeDeclaration in receiver.CandidateTypes)
		{
			var semanticModel = context.Compilation.GetSemanticModel(typeDeclaration.SyntaxTree);
			var typeSymbol = semanticModel.GetDeclaredSymbol(typeDeclaration);

			if (typeSymbol is null)
			{
				continue;
			}

			var members = GetInjectableMembers(typeSymbol, context.Compilation);

			if (members.Count == 0)
			{
				continue;
			}

			var source = GeneratePartialClass(typeSymbol, members);
			context.AddSource($"{typeSymbol.ToDisplayString()}_Inject.g.cs", source);
		}
	}

	private static IReadOnlyList<ISymbol> GetInjectableMembers(INamedTypeSymbol typeSymbol, Compilation compilation)
	{
		return typeSymbol.GetMembers()
			.Where(m => m is IFieldSymbol or IPropertySymbol)
			.Where(m =>
			{
				var attributes = m.GetAttributes();
				return attributes.Any(attr => SymbolEqualityComparer.Default.Equals(
					attr.AttributeClass,
					compilation.GetTypeByMetadataName(InjectAttributeType)));
			})
			.ToList();
	}

	private static string GeneratePartialClass(INamedTypeSymbol typeSymbol, IReadOnlyList<ISymbol> members)
	{
		var sb = new StringBuilder();
		var namespaceName = typeSymbol.ContainingNamespace.ToDisplayString();

		sb.AppendLine("// <auto-generated />");
		sb.AppendLine();

		if (!string.IsNullOrEmpty(namespaceName) && namespaceName != "<global namespace>")
		{
			sb.AppendLine($"namespace {namespaceName}");
			sb.AppendLine("{");
		}

		sb.AppendLine($"    partial class {typeSymbol.Name}");
		sb.AppendLine("    {");
		sb.AppendLine("        public override void Inject(System.Collections.Generic.Queue<object> args)");
		sb.AppendLine("        {");
		sb.AppendLine("            base.Inject(args);");
		sb.AppendLine();

		foreach (var member in members)
		{
			var memberType = member is IFieldSymbol field ? field.Type : ((IPropertySymbol)member).Type;
			sb.AppendLine($"            {member.Name} = ({memberType.ToDisplayString()})args.Dequeue();");
		}

		sb.AppendLine("        }");
		sb.AppendLine("    }");

		if (!string.IsNullOrEmpty(namespaceName) && namespaceName != "<global namespace>")
		{
			sb.AppendLine("}");
		}

		return sb.ToString();
	}

	private class InjectSyntaxReceiver : ISyntaxReceiver
	{
		public List<TypeDeclarationSyntax> CandidateTypes { get; } = [];

		public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
		{
			if (syntaxNode is TypeDeclarationSyntax typeDeclaration &&
			    typeDeclaration.Members.Any(m => m is FieldDeclarationSyntax or PropertyDeclarationSyntax &&
			                                     m.AttributeLists.Count > 0))
			{
				CandidateTypes.Add(typeDeclaration);
			}
		}
	}
}