// using System.Collections.Generic;
// using System.Linq;
// using System.Text;
// using Microsoft.CodeAnalysis;
// using Microsoft.CodeAnalysis.CSharp.Syntax;
// using Microsoft.CodeAnalysis.Text;
//
// namespace Assembler.Generators;
//
// [Generator]
// public class MemberResolverGenerator : ISourceGenerator
// {
// 	private const string DisplayString = "Assembler.Generators.Attributes.GenerateEnumFromMembersAttribute";
//
// 	public void Initialize(GeneratorInitializationContext context)
// 	{
// 		context.RegisterForSyntaxNotifications(() => new SyntaxReceiver());
// 	}
//
// 	public void Execute(GeneratorExecutionContext context)
// 	{
// 		if (context.SyntaxReceiver is not SyntaxReceiver receiver)
// 		{
// 			return;
// 		}
//
// 		foreach (var classDeclaration in receiver.CandidateClasses)
// 		{
// 			var model = context.Compilation.GetSemanticModel(classDeclaration.SyntaxTree);
//
// 			if (model.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
// 			{
// 				continue;
// 			}
//
// 			var attribute = classSymbol.GetAttributes()
// 				.FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == DisplayString);
//
// 			if (attribute is null)
// 			{
// 				continue;
// 			}
//
// 			var typeArgument = attribute.ConstructorArguments.FirstOrDefault().Value as ITypeSymbol;
//
// 			if (typeArgument is null)
// 			{
// 				continue;
// 			}
//
// 			var resolverSource = GenerateMemberResolver(classSymbol, typeArgument);
// 			context.AddSource($"{classSymbol.Name}MemberResolver.g.cs", SourceText.From(resolverSource, Encoding.UTF8));
// 		}
// 	}
//
// 	private static string GenerateMemberResolver(INamedTypeSymbol classSymbol, ITypeSymbol filterType)
// 	{
// 		var sb = new StringBuilder();
// 		sb.AppendLine("// <auto-generated/>");
// 		sb.AppendLine();
//
// 		var namespaceName = classSymbol.ContainingNamespace?.ToDisplayString();
//
// 		if (!string.IsNullOrEmpty(namespaceName) && namespaceName != "<global namespace>")
// 		{
// 			sb.AppendLine($"namespace {namespaceName}");
// 			sb.AppendLine("{");
// 		}
//
// 		sb.AppendLine($"    public static class {classSymbol.Name}MemberResolver");
// 		sb.AppendLine("    {");
// 		sb.AppendLine(
// 			$"        public static {filterType.ToDisplayString()}? ResolveMember({classSymbol.Name}Members member)");
// 		sb.AppendLine("        {");
// 		sb.AppendLine("            return member switch");
// 		sb.AppendLine("            {");
//
// 		var members = MemberHelper.GetMembers(classSymbol, filterType);
// 		var fullyQualifiedName = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
// 			.Replace("global::", "");
//
// 		foreach (var memberName in members)
// 		{
// 			sb.AppendLine(
// 				$"                {classSymbol.Name}Members.{memberName} => {fullyQualifiedName}.{memberName},");
// 		}
//
// 		sb.AppendLine("                _ => null");
// 		sb.AppendLine("            };");
// 		sb.AppendLine("        }");
// 		sb.AppendLine("    }");
//
// 		if (!string.IsNullOrEmpty(namespaceName) && namespaceName != "<global namespace>")
// 		{
// 			sb.AppendLine("}");
// 		}
//
// 		return sb.ToString();
// 	}
//
// 	private class SyntaxReceiver : ISyntaxReceiver
// 	{
// 		public List<ClassDeclarationSyntax> CandidateClasses { get; } = [];
//
// 		public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
// 		{
// 			if (syntaxNode is ClassDeclarationSyntax { AttributeLists.Count: > 0 } classDeclaration)
// 			{
// 				CandidateClasses.Add(classDeclaration);
// 			}
// 		}
// 	}
// }