using System.Collections.Generic;
using Assembler.Parsing.Info;
using Assembler.Parsing.Info.Behaviours;
using UnityEngine;
using CubeGizmoInfo = Assembler.Parsing.Info.Behaviours.CubeGizmoInfo;
using SphereGizmoInfo = Assembler.Parsing.Info.Behaviours.SphereGizmoInfo;

namespace Assembler.Parsing
{
	public delegate BehaviourInfo BehaviourFactory(
		string id,
		IReadOnlyList<ListenerInfo> listeners,
		IReadOnlyDictionary<string, AssemblerValue> props,
		TransformContext ctx);

	public static class BehaviourRegistry
	{
		public readonly static IReadOnlyDictionary<string, BehaviourFactory> All =
			new Dictionary<string, BehaviourFactory>
			{
				["box collider"] = BoxColliderInfo.Create,
				["sphere collider"] = SphereColliderInfo.Create,
				["capsule collider"] = CapsuleColliderInfo.Create,
				["mesh collider"] = MeshColliderInfo.Create,
				["rigidbody"] = RigidbodyInfo.Create,
				["add force"] = AddForceInfo.Create,
				["add impulse"] = AddImpulseInfo.Create,
				["add torque"] = AddTorqueInfo.Create,
				["set velocity"] = SetVelocityInfo.Create,
				["set angular velocity"] = SetAngularVelocityInfo.Create,
				["velocity"] = VelocityInfo.Create,
				["acceleration"] = AccelerationInfo.Create,
				["drag"] = DragInfo.Create,
				["speed limit"] = SpeedLimitInfo.Create,
				["move towards"] = MoveTowardsInfo.Create,
				["smooth move"] = SmoothMoveInfo.Create,
				["clamp position"] = ClampPositionInfo.Create,
				["wrap position"] = WrapPositionInfo.Create,
				["translate"] = TranslateInfo.Create,
				["angular velocity"] = AngularVelocityInfo.Create,
				["rotate"] = RotateInfo.Create,
				["rotation setter"] = SetRotationInfo.Create,
				["move animation"] = MoveAnimationInfo.Create,
				["scale animation"] = ScaleAnimationInfo.Create,
				["rotate animation"] = RotateAnimationInfo.Create,
				["key hold trigger"] = KeyHoldTriggerInfo.Create,
				["key down trigger"] = KeyDownTriggerInfo.Create,
				["key up trigger"] = KeyUpTriggerInfo.Create,
				["mouse button trigger"] = MouseButtonTriggerInfo.Create,
				["mouse position trigger"] = MousePositionTriggerInfo.Create,
				["scroll wheel trigger"] = ScrollWheelTriggerInfo.Create,
				["axis trigger"] = AxisTriggerInfo.Create,
				["input action"] = InputActionTriggerInfo.Create,
				["gamepad button trigger"] = GamepadButtonTriggerInfo.Create,
				["tap trigger"] = TapTriggerInfo.Create,
				["double tap trigger"] = DoubleTapTriggerInfo.Create,
				["long press trigger"] = LongPressTriggerInfo.Create,
				["swipe trigger"] = SwipeTriggerInfo.Create,
				["drag trigger"] = DragTriggerInfo.Create,
				["pinch and rotate trigger"] = PinchAndRotateTriggerInfo.Create,
				["condition"] = ConditionInfo.Create,
				["timer trigger"] = TimerTriggerInfo.Create,
				["deferred trigger"] = DeferredTriggerInfo.Create,
				["debounced trigger"] = DebouncedTriggerInfo.Create,
				["throttled trigger"] = ThrottledTriggerInfo.Create,
				["on start trigger"] = OnStartTriggerInfo.Create,
				["interval trigger"] = IntervalTriggerInfo.Create,
				["every frame trigger"] = EveryFrameTriggerInfo.Create,
				["collision enter trigger"] = CollisionEnterTriggerInfo.Create,
				["trigger enter trigger"] = TriggerEnterTriggerInfo.Create,
				["trigger exit trigger"] = TriggerExitTriggerInfo.Create,
				["trigger stay trigger"] = TriggerStayTriggerInfo.Create,
				["collision exit trigger"] = CollisionExitTriggerInfo.Create,
				["collision stay trigger"] = CollisionStayTriggerInfo.Create,
				["when all"] = WhenAllInfo.Create,
				["when any"] = WhenAnyInfo.Create,
				["spawner"] = SpawnerInfo.Create,
				["destroy"] = DestroyInfo.Create,
				["position setter"] = SetPositionInfo.Create,
				["camera"] = CameraInfo.Create,
				["condition gate"] = ConditionGateInfo.Create,
				["inverse condition gate"] = InverseConditionGateInfo.Create,
				["exclusive trigger"] = ExclusiveTriggerInfo.Create,
				["state machine"] = StateMachineInfo.Create,
				["vector variable setter"] = VariableSetterInfo<Vector3>.Create,
				["int variable setter"] = VariableSetterInfo<int>.Create,
				["float variable setter"] = VariableSetterInfo<float>.Create,
				["bool variable setter"] = VariableSetterInfo<bool>.Create,
				["string variable setter"] = VariableSetterInfo<string>.Create,
				["colour variable setter"] = VariableSetterInfo<Color>.Create,

				["vector list add"] = ListAddInfo<Vector3>.Create,
				["vector list insert"] = ListInsertInfo<Vector3>.Create,
				["vector list remove at"] = ListRemoveAtInfo<Vector3>.Create,
				["vector list remove"] = ListRemoveInfo<Vector3>.Create,
				["vector list set at"] = ListSetAtInfo<Vector3>.Create,
				["vector list set"] = ListSetInfo<Vector3>.Create,
				["vector list add range"] = ListAddRangeInfo<Vector3>.Create,
				["vector list clear"] = ListClearInfo<Vector3>.Create,
				["vector list loop trigger"] = ListLoopTriggerInfo<Vector3>.Create,

				["int list add"] = ListAddInfo<int>.Create,
				["int list insert"] = ListInsertInfo<int>.Create,
				["int list remove at"] = ListRemoveAtInfo<int>.Create,
				["int list remove"] = ListRemoveInfo<int>.Create,
				["int list set at"] = ListSetAtInfo<int>.Create,
				["int list set"] = ListSetInfo<int>.Create,
				["int list add range"] = ListAddRangeInfo<int>.Create,
				["int list clear"] = ListClearInfo<int>.Create,
				["int list loop trigger"] = ListLoopTriggerInfo<int>.Create,

				["float list add"] = ListAddInfo<float>.Create,
				["float list insert"] = ListInsertInfo<float>.Create,
				["float list remove at"] = ListRemoveAtInfo<float>.Create,
				["float list remove"] = ListRemoveInfo<float>.Create,
				["float list set at"] = ListSetAtInfo<float>.Create,
				["float list set"] = ListSetInfo<float>.Create,
				["float list add range"] = ListAddRangeInfo<float>.Create,
				["float list clear"] = ListClearInfo<float>.Create,
				["float list loop trigger"] = ListLoopTriggerInfo<float>.Create,

				["bool list add"] = ListAddInfo<bool>.Create,
				["bool list insert"] = ListInsertInfo<bool>.Create,
				["bool list remove at"] = ListRemoveAtInfo<bool>.Create,
				["bool list remove"] = ListRemoveInfo<bool>.Create,
				["bool list set at"] = ListSetAtInfo<bool>.Create,
				["bool list set"] = ListSetInfo<bool>.Create,
				["bool list add range"] = ListAddRangeInfo<bool>.Create,
				["bool list clear"] = ListClearInfo<bool>.Create,
				["bool list loop trigger"] = ListLoopTriggerInfo<bool>.Create,

				["string list add"] = ListAddInfo<string>.Create,
				["string list insert"] = ListInsertInfo<string>.Create,
				["string list remove at"] = ListRemoveAtInfo<string>.Create,
				["string list remove"] = ListRemoveInfo<string>.Create,
				["string list set at"] = ListSetAtInfo<string>.Create,
				["string list set"] = ListSetInfo<string>.Create,
				["string list add range"] = ListAddRangeInfo<string>.Create,
				["string list clear"] = ListClearInfo<string>.Create,
				["string list loop trigger"] = ListLoopTriggerInfo<string>.Create,

				["colour list add"] = ListAddInfo<Color>.Create,
				["colour list insert"] = ListInsertInfo<Color>.Create,
				["colour list remove at"] = ListRemoveAtInfo<Color>.Create,
				["colour list remove"] = ListRemoveInfo<Color>.Create,
				["colour list set at"] = ListSetAtInfo<Color>.Create,
				["colour list set"] = ListSetInfo<Color>.Create,
				["colour list add range"] = ListAddRangeInfo<Color>.Create,
				["colour list clear"] = ListClearInfo<Color>.Create,
				["colour list loop trigger"] = ListLoopTriggerInfo<Color>.Create,

				["active poll"] = ActivePollInfo.Create,
				["set active"] = SetActiveInfo.Create,
				["set timescale"] = SetTimeScaleInfo.Create,
				["toggle active"] = ToggleActiveInfo.Create,

				["sprite"] = SpriteInfo.Create,
				["voxel mesh"] = VoxelMeshInfo.Create,
				["primitive"] = PrimitiveInfo.Create,
				["audio source"] = AudioSourceInfo.Create,
				["sphere gizmo"] = SphereGizmoInfo.Create,
				["cube gizmo"] = CubeGizmoInfo.Create,
				["line gizmo"] = LineGizmoInfo.Create,
				["ui canvas"] = UICanvasInfo.Create,
				["ui container"] = UIContainerInfo.Create,
				["text label"] = TextLabelInfo.Create,
				["ui button"] = UIButtonInfo.Create,
				["ui slider"] = UISliderInfo.Create,
			};
	}
}
