using System.Collections.Generic;
using Assembler.Parsing.Info.Behaviours;
using UnityEngine;

namespace Assembler.Behaviours.Visual
{
	/// <summary>
	/// The mesh behind every <see cref="ShapeKind"/>, and the one place a shape becomes a GameObject.
	/// Both <c>primitive</c> and <c>model</c> build their children through here.
	/// </summary>
	/// <remarks>
	/// The meshes are project assets under <c>Assets/Resources/Meshes</c>, authored by
	/// <c>Tools/blender/build_primitives.py</c>, rather than <see cref="GameObject.CreatePrimitive"/>:
	/// Unity ships only six shapes and its enum cannot be extended, and its cylinder, capsule and plane
	/// are not unit-sized. Every mesh here is 1 x 1 x 1 — the capsule alone excepted, because a capsule
	/// of radius 0.5 and height 1 is a sphere — so a part's <c>Size</c> is its world bounding box with
	/// nothing to divide out.
	/// One <see cref="Mesh"/> instance is shared by every part that names a shape: <see cref="Resources"/>
	/// hands back the same imported asset each time, and the dictionary just saves re-walking it.
	/// </remarks>
	public static class PrimitiveMeshes
	{
		private static readonly Dictionary<ShapeKind, Mesh> Meshes = new();

		private static Material? _material;

		/// <summary>The shared mesh for <paramref name="shape"/>.</summary>
		public static Mesh For(ShapeKind shape)
		{
			if (Meshes.TryGetValue(shape, out var cached) && cached != null)
			{
				return cached;
			}

			var mesh = Resources.Load<Mesh>($"Meshes/{shape}");

			if (mesh == null)
			{
				throw new MissingReferenceException(
					$"No mesh for shape '{shape}' at Resources/Meshes/{shape}. The primitive meshes are " +
					"generated by Tools/blender/build_primitives.py and must be imported into the project.");
			}

			Meshes[shape] = mesh;
			return mesh;
		}

		/// <summary>
		/// Builds one mesh child of <paramref name="parent"/>: the shape's mesh, the shared primitive
		/// material, and the <see cref="PrimitiveShape"/> marker <c>part colliders</c> reads. The child is
		/// visual only — no collider, because collision in Assembler is declared explicitly.
		/// </summary>
		public static GameObject Create(ShapeKind shape, string name, Transform parent)
		{
			var host = new GameObject(name);
			host.transform.SetParent(parent, false);

			host.AddComponent<MeshFilter>().sharedMesh = For(shape);
			host.AddComponent<MeshRenderer>().sharedMaterial = Material;
			host.AddComponent<PrimitiveShape>().Shape = shape;

			return host;
		}

		// Cached across parts: a model of a dozen parts would otherwise hit Resources a dozen times, and
		// every part shares the one material anyway (per-part colour goes through a property block).
		private static Material Material
		{
			get
			{
				if (_material == null)
				{
					_material = Resources.Load<Material>("Materials/Primitive");
				}

				return _material!;
			}
		}
	}
}
